application: second-friend
version: 1
runtime: python27
api_version: 1
threadsafe: true

#default_expiration: "4d 5h"

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always

- url: /static
  static_dir: static

- url: /.*
  script: main.app